name: dartminer
author: Travis Tidwell <travist349@gmail.com>
version: 0.0.6
homepage: https://github.com/travist/dartminer
description: A Bitcoin miner with Dart language.
dependencies:
  crypto: any
  unittest: any
  utf: '>=0.9.0 <0.9.1'
