name: dartminer
version: 0.0.12
author: Travis Tidwell <travist349@gmail.com>
description: A Bitcoin miner with Dart language.
homepage: https://github.com/travist/dartminer
dependencies:
  crypto: '>=0.9.0 <0.9.1'
  unittest: '>=0.10.0 <0.10.1'
  utf: '>=0.9.0 <0.9.1'
